### ISSUE TITLE
How effective is mamba in BAA? Is there a MAE?

### ISSUE THREAD

**Issue by KARENLHAO** [SCU-zly/BAAMamba#1]

**Comment by SCU-zly** [comment]
Thank you for your question!

Mamba has proven to be quite effective in the context of BAA. Given that Vision Mamba is designed to handle casual information, it aligns well with the visual characteristics typical of BAA. Our internal evaluations have shown competitive results in this area.
Additionally, our codebase includes the implementation of Mean Absolute Error (MAE) as a metric, which you can use to assess the model's performance quantitatively.
I hope this answers your query. If you have any more questions or need further details, please feel free to ask!
